name: 'Build and Test'

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'
          registry-url: https://npm.pkg.github.com

      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: npm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: action
        uses: ./
