name: 'Build and Test'

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Check out the source code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Setup Node.js environment
        uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854 # tag=v3.1.1
        with:
          node-version: '16'
          cache: npm

      - name: Update npm
        run: npm i -g npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run all

  test:
    name: Test
    runs-on: ubuntu-latest
    ## If the action needs to access a secret:
    # if: |
    #   github.event_name == 'workflow_dispatch' ||
    #   github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name && github.event.sender.login != 'dependabot[bot]' ||
    #   github.event_name == 'push' && !contains(github.event.head_commit.message, '[ci skip]')
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Check out the source code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Test the action
        id: action
        uses: ./
